DROP TABLE IF EXISTS `account_tran`;
CREATE TABLE `account_tran` (
                                `ID` bigint NOT NULL AUTO_INCREMENT,
                                `ACCOUNT_ID` int NOT NULL,
                                `DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `LOGDATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `TRAN_TYPE` varchar(10) NOT NULL,
                                `AMOUNT_REAL` decimal(10,2) DEFAULT NULL,
                                `BALANCE_REAL` decimal(10,2) DEFAULT NULL,
                                `PLATFORM_TRAN_ID` varchar(100) DEFAULT NULL,
                                `GAME_TRAN_ID` varchar(100) DEFAULT NULL,
                                `GAME_ID` varchar(100) DEFAULT NULL,
                                `PLATFORM_ID` int DEFAULT NULL,
                                `payment_id` int DEFAULT NULL,
                                `ROLLED_BACK` int DEFAULT '0',
                                `ROLLBACK_TRAN_ID` bigint DEFAULT NULL,
                                `AMOUNT_RELEASED_BONUS` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `AMOUNT_PLAYABLE_BONUS` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `BALANCE_RELEASED_BONUS` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `BALANCE_PLAYABLE_BONUS` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `AMOUNT_UNDERFLOW` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `AMOUNT_RAW_LOYALTY` bigint NOT NULL DEFAULT '0',
                                `BALANCE_RAW_LOYALTY` bigint NOT NULL DEFAULT '0',
                                `AMOUNT_FREE_BET` decimal(10,2) NOT NULL DEFAULT '0.00',
                                `GAME_INSTANCE_ID` bigint DEFAULT NULL,
                                `TRANSACTION_ON_HOLD_ID` bigint DEFAULT NULL,
                                `CHANNEL` varchar(25) DEFAULT NULL,
                                `GAME_SESSION_ID` varchar(255) DEFAULT NULL,
                                `EXTERNAL_GAME_SESSION_ID` varchar(255) DEFAULT NULL,
                                PRIMARY KEY (`ID`),
                                KEY `IDX_ACCOUNT_TRAN_1` (`ACCOUNT_ID`, `DATETIME`) USING BTREE,
                                KEY `IDX_ACCOUNT_TRAN_DATETIME` (`DATETIME`) USING BTREE,
                                KEY `IDX_ACCOUNT_TRAN_GAME_ID` (`GAME_ID`) USING BTREE,
                                KEY `IDX_ACCOUNT_TRAN_2` (`GAME_TRAN_ID`) USING BTREE,
                                KEY `IDX_ACCOUNT_TRAN_3` (`PLATFORM_TRAN_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6996 DEFAULT CHARSET=utf8mb3;

