ALTER TABLE `account_tran`

    ADD INDEX `IDX_ACCOUNT_TRAN_DATETIME` (`DATETIME`),
    ADD INDEX `IDX_ACCOUNT_TRAN_GAME_ID` (`GAME_ID`),

    DROP INDEX `IDX_ACCOUNT_TRAN_2`,
    ADD UNIQUE INDEX `IDX_ACCOUNT_TRAN_2` (`GAME_TRAN_ID`),

    DROP INDEX `IDX_ACCOUNT_TRAN_3`,
    ADD UNIQUE INDEX `IDX_ACCOUNT_TRAN_3` (`PLATFORM_TRAN_ID`);