EXPLAIN SELECT
    ACCOUNT_ID,
    SUM(CASE WHEN TRAN_TYPE = 'GAME_BET' THEN AMOUNT_REAL ELSE 0 END) AS bet_sum,
    SUM(CASE WHEN TRAN_TYPE = 'GAME_WIN' THEN AMOUNT_REAL ELSE 0 END) AS win_sum,
    SUM(CASE WHEN TRAN_TYPE = 'GAME_WIN' THEN AMOUNT_REAL ELSE 0 END)
      + SUM(CASE WHEN TRAN_TYPE = 'GAME_BET' THEN AMOUNT_REAL ELSE 0 END) AS net
FROM account_tran
WHERE
 `DATETIME` >= '2025-07-28 13:00:40' AND `DATETIME` <= '2025-07-29 13:00:40' 
AND TRAN_TYPE IN ('GAME_BET', 'GAME_WIN') AND
GAME_ID ='SPORTSBOOK2.0' AND
PLATFORM_TRAN_ID = '510000096174' AND
GAME_TRAN_ID = '510000096174' 
GROUP BY ACCOUNT_ID;



EXPLAIN SELECT
          ID,
          ACCOUNT_ID,
          DATETIME,
          TRAN_TYPE,
          PLATFORM_TRAN_ID,
          GAME_TRAN_ID,
          GAME_ID,
     
          (
      	    COALESCE(AMOUNT_REAL, 0)
      	    + COALESCE(AMOUNT_RELEASED_BONUS, 0)
      	    + COALESCE(AMOUNT_PLAYABLE_BONUS, 0)
      	    + COALESCE(AMOUNT_UNDERFLOW, 0)
      	    + COALESCE(AMOUNT_FREE_BET, 0)
      	) AS amount,
     
          (
              COALESCE(BALANCE_REAL, 0)
              + COALESCE(BALANCE_RELEASED_BONUS, 0)
              + COALESCE(BALANCE_PLAYABLE_BONUS, 0)      
          ) AS balance
      FROM account_tran 
	WHERE
	  #GAME_ID ='SPORTSBOOK2.0' AND
	  #PLATFORM_TRAN_ID = '510000096174' AND
	  GAME_TRAN_ID = '510000096174' AND
	 `DATETIME` >= '2025-07-28 13:00:40' AND `DATETIME` <= '2025-09-29 13:00:40';

SELECT
    GAME_ID,
    COUNT(DISTINCT PLATFORM_ID) AS platform_count
FROM account_tran
GROUP BY GAME_ID
HAVING COUNT(DISTINCT PLATFORM_ID) > 1;

SELECT COUNT(DISTINCT LEFT(column_name, 10)) FROM table;


select
  count(accounttra0_.ID) as col_0_0_ 
from
  account_tran accounttra0_ 
where
  1=1 
  and accounttra0_.DATETIME>='2025-07-28 13:00:40' 
  and accounttra0_.DATETIME<='2025-07-28 13:00:40'